package main

type Book struct {
	bookNumber string
	fullName   string
}

func getBookNumbers() map[string]Book {
	bookNumbers := map[string]Book{
		"Gen":    {"01", "Genesis"},
		"Exo":    {"02", "Exodus"},
		"Lev":    {"03", "Leviticus"},
		"Num":    {"04", "Numbers"},
		"Deut":   {"05", "Deuteronomy"},
		"Josh":   {"06", "Joshua"},
		"Judg":   {"07", "Judges"},
		"Ruth":   {"08", "Ruth"},
		"1Sam":   {"09", "1Samuel"},
		"2Sam":   {"10", "2Samuel"},
		"1Kings": {"11", "1Kings"},
		"2Kings": {"12", "2Kings"},
		"1Chron": {"13", "1Chronicles"},
		"2Chron": {"14", "2Chronicles"},
		"Ezra":   {"15", "Ezra"},
		"Neh":    {"16", "Nehemiah"},
		"Esth":   {"17", "Esther"},
		"Job":    {"18", "Job"},
		"Psa":    {"19", "Psalms"},
		"Prov":   {"20", "Proverbs"},
		"Eccl":   {"21", "Ecclesiastes"},
		"SS":     {"22", "SongofSongs"},
		"Isa":    {"23", "Isaiah"},
		"Jer":    {"24", "Jeremiah"},
		"Lam":    {"25", "Lamentations"},
		"Ezek":   {"26", "Ezekiel"},
		"Dan":    {"27", "Daniel"},
		"Hosea":  {"28", "Hosea"},
		"Joel":   {"29", "Joel"},
		"Amos":   {"30", "Amos"},
		"Obad":   {"31", "Obadiah"},
		"Jonah":  {"32", "Jonah"},
		"Micah":  {"33", "Micah"},
		"Nahum":  {"34", "Nahum"},
		"Hab":    {"35", "Habakkuk"},
		"Zeph":   {"36", "Zephaniah"},
		"Hag":    {"37", "Haggai"},
		"Zech":   {"38", "Zechariah"},
		"Mal":    {"39", "Malachi"},
		"Matt":   {"40", "Matthew"},
		"Mark":   {"41", "Mark"},
		"Luke":   {"42", "Luke"},
		"John":   {"43", "John"},
		"Acts":   {"44", "Acts"},
		"Rom":    {"45", "Romans"},
		"1Cor":   {"46", "1Corinthians"},
		"2Cor":   {"47", "2Corinthians"},
		"Gal":    {"48", "Galatians"},
		"Eph":    {"49", "Ephesians"},
		"Phil":   {"50", "Philippians"},
		"Col":    {"51", "Colossians"},
		"1Thes":  {"52", "1Thessalonians"},
		"2Thes":  {"53", "2Thessalonians"},
		"1Tim":   {"54", "1Timothy"},
		"2Tim":   {"55", "2Timothy"},
		"Titus":  {"56", "Titus"},
		"Philem": {"57", "Philemon"},
		"Heb":    {"58", "Hebrews"},
		"James":  {"59", "James"},
		"1Pet":   {"60", "1Peter"},
		"2Pet":   {"61", "2Peter"},
		"1John":  {"62", "1John"},
		"2John":  {"63", "2John"},
		"3John":  {"64", "3John"},
		"Jude":   {"65", "Jude"},
		"Rev":    {"66", "Revelation"},
	}

	return bookNumbers
}
